name: Panto
options:
  bundleIdPrefix: org.panto.ios
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: 15.0
  developmentLanguage: "zh-Hans"
  knownRegions:
    - "zh-Hans"
    - "en"
    - "Base"

settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "9S948B2LF8"
    CODE_SIGN_STYLE: "Automatic"
    EXCLUDED_ARCHS[sdk=iphonesimulator*]: "x86_64"
    ONLY_ACTIVE_ARCH: "YES"

targets:
  PantoShared:
    type: library.static
    platform: iOS
    sources:
      - path: Shared
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.panto.ios.PantoShared
      SKIP_INSTALL: "YES"
      DEFINES_MODULE: "YES"

  PantoTunnel:
    type: app-extension
    platform: iOS
    sources:
      - path: PantoTunnel
    dependencies:
      - target: PantoShared
      - framework: Frameworks/PantoKit.xcframework
        embed: false
    info:
      path: PantoTunnel/Info.plist
      properties:
        CFBundlePackageType: "XPC!"
        CFBundleShortVersionString: "0.1.0-alpha"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.networkextension.packet-tunnel"
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).PacketTunnelProvider"
    entitlements:
      path: PantoTunnel/PantoTunnel.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.application-groups:
          - group.org.panto.ios
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.panto.ios.PantoTunnel
      SKIP_INSTALL: "YES"

  PantoApp:
    type: application
    platform: iOS
    sources:
      - path: PantoApp
    dependencies:
      - target: PantoShared
      - target: PantoTunnel
        embed: true
      - framework: Frameworks/PantoKit.xcframework
        embed: true
    info:
      path: PantoApp/Info.plist
      properties:
        CFBundleDisplayName: "Panto"
        CFBundleShortVersionString: "0.1.0-alpha"
        CFBundleVersion: "1"
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CFBundleURLTypes:
          - CFBundleURLName: org.panto.ios
            CFBundleURLSchemes:
              - panto
              - clash
    entitlements:
      path: PantoApp/PantoApp.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.application-groups:
          - group.org.panto.ios
    settings:
      PRODUCT_NAME: "Panto"
      PRODUCT_BUNDLE_IDENTIFIER: org.panto.ios
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: "AppIcon-Day AppIcon-Twilight AppIcon-Night"
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "YES"
